[package]
name = "paralleler"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["sqlx_sqlite"]

[default.databases.paralleler]
url = "~/paralleler.db"
